name: CD_server_pro

on:
  workflow_dispatch:

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.3'
          cache-dependency-path: packages/server/src/go.sum

      - name: Build Go binary
        working-directory: packages/server/src
        run: |
          go mod download
          CGO_ENABLED=0 GOOS=linux go build -v -ldflags="-s -w" -o ../server-bin ./cmd/server

      - name: SCP binary to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "packages/server/server-bin"
          target: "~/linked-crystal-server"
          strip_components: 1

      - name: Deploy and Restart Service via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Mover binario a sitio final y dar permisos
            sudo mv ~/linked-crystal-server/server-bin /usr/local/bin/websocket-server-pro
            sudo chmod +x /usr/local/bin/websocket-server-pro

            # Configurar variables de entorno (como en dev)
            sudo tee /etc/default/websocket-server-pro > /dev/null <<EOF
            STATIC_TOKEN=${{ secrets.STATIC_TOKEN }}
            SERVERS=${{ vars.SERVERS }}
            PORT=${{ vars.PORT }}
            EOF

            # Reiniciar servicio systemd
            sudo systemctl daemon-reload
            sudo systemctl restart websocket-server-pro
            sudo systemctl status websocket-server-pro --no-pager
