name: CD_server_pro

on:
  workflow_dispatch:

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.3'
          cache-dependency-path: packages/server/src/go.sum

      - name: Build Go binary
        working-directory: packages/server/src
        run: |
          go mod download
          CGO_ENABLED=0 GOOS=linux go build -v -ldflags="-s -w" -o ../server-bin ./cmd/server

      - name: SCP binary to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "packages/server/server-bin"
          target: "~/linked-crystal-server"
          strip_components: 1

      - name: Deploy and Restart Service via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Crear el archivo de servicio systemd si no existe
            sudo tee /etc/systemd/system/websocket-server-pro.service > /dev/null <<EOF
            [Unit]
            Description=Websocket Server Pro
            After=network.target

            [Service]
            Type=simple
            User=${{ secrets.SERVER_USER }}
            ExecStart=/usr/local/bin/websocket-server-pro
            Restart=always
            EnvironmentFile=/etc/default/websocket-server-pro

            [Install]
            WantedBy=multi-user.target
            EOF

            # 2. Mover el binario a su ruta final
            # Explicación ruta: target (~/linked-crystal-server) + carpeta restante tras strip (server/)
            sudo mv ~/linked-crystal-server/server/server-bin /usr/local/bin/websocket-server-pro
            sudo chmod +x /usr/local/bin/websocket-server-pro

            # 3. Configurar variables de entorno (Añadido ENV=production)
            sudo tee /etc/default/websocket-server-pro > /dev/null <<EOF
            ENV=production
            STATIC_TOKEN=${{ secrets.STATIC_TOKEN }}
            SERVERS=${{ vars.SERVERS }}
            PORT=${{ vars.PORT }}
            EOF

            # 4. Recargar, habilitar y reiniciar
            sudo systemctl daemon-reload
            sudo systemctl enable websocket-server-pro
            sudo systemctl restart websocket-server-pro
            
            # Verificamos que esté corriendo
            sudo systemctl status websocket-server-pro --no-pager