name: DEV_CI_DEVEX

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Makefile'
      - '.devcontainer/**'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-devex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and run Devex Integrity Test
        run: |
          # Use the Dockerfile to run the test in a clean environment
          docker build -t devex-tester .devcontainer
          docker run --rm -v $(pwd):/work -w /work devex-tester make test-devex
