on:
  push:
    branches: ["main"]
    paths:
      - '.github/devex/docs/**'
      - '.github/workflows/PRO_CD_WIKI.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync Wiki
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git clone "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.wiki.git" wiki_repo
          
          find wiki_repo -maxdepth 1 -not -name '.git' -not -name 'wiki_repo' -not -name '.' -exec rm -rf {} +
          cp -rv .github/devex/docs/. wiki_repo/
          
          cd wiki_repo
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Wiki update: $GITHUB_SHA"
            git push origin HEAD
          fi